h = input("Digite algo: ")
print('{} é do tipo'.format(h), type(h))
print('{} é numérico?'.format(h), h.isnumeric())
print('{} é alfabético?'.format(h), h.isalpha())
print('{} é alfanumérico?'.format(h), h.isalnum())
print('{} contém somente espaços?'.format(h), h.isspace())
print('{} está escrito somente em letras minúsculas?'.format(h), h.islower())
print('{} está escrito somente em letras maiúsculas?'.format(h), h.isupper())
print('{} está com a primeira letra maiúscula?'.format(h), h.istitle())
